import {
    APPWRITE_URL,
    APPWRITE_Project_ID,
    APPWRITE_DATABASE_TODO_ID,
    APPWRITE_COLLECTION_SAVEDTODO_ID,
    APPWRITE_COLLECTION_SAVEDUSER_ID
} from "@env"

export default {
    APPWRITE_URL,
    APPWRITE_Project_ID,
    APPWRITE_DATABASE_TODO_ID,
    APPWRITE_COLLECTION_SAVEDTODO_ID,
    APPWRITE_COLLECTION_SAVEDUSER_ID
}